from typing import Tuple

Vec3 = Tuple[float, float, float]

class Buffer: ...

class Source:
    ended: bool

    def stop(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...

def init() -> None: ...
def update(position: Vec3, velocity: Vec3, direction: Vec3, up: Vec3, gain: float) -> None: ...
def pause() -> None: ...
def resume() -> None: ...
def load(name: str, data: bytes | str | tuple) -> None: ...
def unload(name: str) -> None: ...
def play(
    name: str, position: Vec3, velocity: Vec3, direction: Vec3, pitch: float, gain: float, relative: bool, loop: bool
) -> Source: ...
