name: release

on:
  workflow_dispatch:

jobs:

  sdist:
    name: Package source
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: deps
        run: python -m pip install -U pip wheel setuptools

      - name: sdist
        run: python setup.py sdist -d package

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: package-source
          path: package/*.tar.gz

  wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    env:
      CIBW_SKIP: pp*

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: deps
        run: python -m pip install -U cibuildwheel

      - name: wheels
        run: python -m cibuildwheel --output-dir package

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ matrix.os }}
          path: package/*.whl

  merge:
    name: Merge Artifacts
    runs-on: ubuntu-latest
    needs:
      - sdist
      - wheels

    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          delete-merged: true
